services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_octane_app
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor/
#            - /var/www/vendor/ #Giữ thư mục vendor bên trong container để tránh bị ghi đè bởi host (do host chưa có vendor trước khi chạy composer install).
            - /var/www/storage/
            - /var/www/bootstrap/cache/
            - .env:/var/www/.env
        ports:
            - "8000:8000"
            - "5173:5173"
        depends_on:
            - db
        networks:
            - laravel_network

    db:
        image: mysql:8.4.4
        container_name: laravel_octane_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_USERNAME}
            MYSQL_USER: ${DB_PASSWORD}
        volumes:
            - data_db:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        container_name: laravel_octane_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    data_db:
